baseURL = 'https://zhaowork.ca'
languageCode = 'en-us'
title = 'IT工作坊'
theme = 'PaperMod'
paginate = 5

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Products'
  pageRef = '/products'
  weight = 20
[[menu.main]]
  name = 'Services'
  pageRef = '/services'
  weight = 30
