baseURL = 'https://zhaowork.ca'
languageCode = 'en-us'
title = 'IT工作坊'
theme = 'PaperMod'
paginate = 5

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Resume'
  pageRef = '/tags/resume/'
  weight = 20
[[menu.main]]
  name = 'Interview'
  pageRef = '/tags/interview/'
  weight = 30
[[menu.main]]
  name = 'Guaid'
  pageRef = '/tags/guaid/'
  weight = 40
[[menu.main]]
  name = 'Resouce'
  pageRef = '/tags/resouce/'
  weight = 50